from __future__ import annotations

from .data.combat_content import BOSSES, COMBAT_ENCOUNTERS, ENEMY_ARCHETYPES, ENEMY_TRAITS
from .data.progression_content import GEAR_ITEMS, PERK_TREES, PERKS, RECIPES, WEAPON_LOADOUTS
from .data.social_content import COLLECTIONS, FAMILY_SUPPORT, FARMING_LANES, INTEGRATION_TRACKS
from .data.world_content import (
    ENDING_PHASES,
    HUB_FEATURES,
    REGION_INTEL,
    REGIONS,
    STORY_CHAPTERS,
    TRAILS,
    WORLD_STATE,
    WORLD_TIERS,
)
from .models import ActivityDefinition

PROJECT_NAME = "John Marston: Ashes of the Frontier"
LEVEL_CAP = 50
PRIMARY_HUB = "Beecher's Hope"
FIRST_NAMED_BOSS = "Silas Redd, The Fence of Ash"
FINAL_MASTERMIND = "The Surveyor"

FIRST_TEN_HOUR_SCRIPT: tuple[ActivityDefinition, ...] = (
    ActivityDefinition(
        activity_id="beechers_hope_defense",
        name="Beecher's Hope Defense",
        xp=420,
        materials={"iron scrap": 3, "treated leather": 2, "gun oil concentrate": 1},
        home_upgrades=0,
        completed_trails=(),
        discovered_regions=("west_elizabeth",),
        farming_gains={"lane.frontier_work": 2},
        network_gains={"track.jobs": 1},
        affinity_changes={"affinity.abigail": 10},
        lifestyle_gains={"homestead": 1, "field_medicine": 1},
        region_progress=("west_elizabeth",),
        completed_chapters=("chapter_1",),
        notes="Opening raid, first ledger clue, and first home defense rhythm.",
    ),
    ActivityDefinition(
        activity_id="dead_courier_recovery",
        name="Dead Courier Recovery",
        xp=280,
        materials={"spring assemblies": 1, "saint cards": 1, "brass fittings": 1},
        items={"Courier Satchel Seal": 1, "Dead Courier Satchel": 1},
        completed_trails=("trail.main.dead_courier_satchel",),
        discovered_regions=("west_elizabeth",),
        network_gains={"track.jobs": 1, "track.bounties": 1},
        affinity_changes={"affinity.jack": 5},
        lifestyle_gains={"trade": 1},
        blueprints=("Trail Mechanic Sketch",),
        completed_chapters=("chapter_2",),
        region_progress=("west_elizabeth",),
        notes="The first courier recovery turns the opening rumor into a real broker trail.",
    ),
    ActivityDefinition(
        activity_id="blackwater_contracts",
        name="Blackwater Contract Sweep",
        xp=520,
        materials={"spring assemblies": 2, "saint cards": 1, "brass fittings": 1},
        items={"Blackwater Safehouse Ledger": 1},
        completed_trails=("trail.main.blood_marked_ledger", "trail.contract.blackwater_broker"),
        discovered_regions=("west_elizabeth",),
        farming_gains={"lane.contract": 2},
        network_gains={"track.contracts": 2, "track.bounties": 1, "track.duels": 1},
        affinity_changes={"affinity.uncle": 8},
        lifestyle_gains={"trade": 1, "gunsmithing": 1},
        blueprints=("Blackwater Ballistics Notes", "Blackwater Peacebreaker Diagram"),
        completed_chapters=("chapter_3",),
        region_progress=("west_elizabeth",),
        notes="First lawful contract loop and city-node pressure.",
    ),
    ActivityDefinition(
        activity_id="great_plains_salvage",
        name="Great Plains Salvage Run",
        xp=460,
        materials={"iron scrap": 4, "hardwood": 4, "treated leather": 2},
        completed_trails=("trail.contract.great_plains_salvage",),
        discovered_regions=("great_plains",),
        farming_gains={"lane.raider": 2, "lane.frontier_work": 1},
        network_gains={"track.stagecoaches": 1},
        affinity_changes={"affinity.abigail": 3, "affinity.uncle": 6},
        lifestyle_gains={"salvaging": 1, "horse_handling": 1},
        region_progress=("great_plains",),
        notes="Supply raid and salvage economy foundation.",
    ),
    ActivityDefinition(
        activity_id="rusk_collectors_dog_hunt",
        name="Rusk, The Collector's Dog",
        xp=480,
        materials={"iron scrap": 2, "silver fittings": 1, "gun oil concentrate": 1},
        items={"Collector's Dog Badge": 1},
        completed_trails=("trail.elite.rusk_collectors_dog",),
        discovered_regions=("west_elizabeth", "great_plains"),
        farming_gains={"lane.contract": 1, "lane.boss": 1},
        network_gains={"track.bounties": 1, "track.duels": 1},
        affinity_changes={"affinity.jack": 4, "affinity.uncle": 4},
        lifestyle_gains={"gunsmithing": 1, "trade": 1},
        blueprints=("Silas Repeater Schematic",),
        region_progress=("west_elizabeth", "great_plains"),
        notes="First named elite kill with a real identity, route owner, and boss-prep schematic payoff.",
    ),
    ActivityDefinition(
        activity_id="tall_trees_hunt",
        name="Tall Trees Elite Hunt",
        xp=510,
        materials={"silver fittings": 2, "preserved herbs": 3, "collector bones": 1, "treated leather": 1},
        relics=1,
        discovered_bosses=("boss.tall_trees_tracker_king",),
        discovered_regions=("great_plains",),
        farming_gains={"lane.hunter": 2, "lane.boss": 1},
        network_gains={"track.bounties": 1},
        affinity_changes={"affinity.jack": 8},
        lifestyle_gains={"hunting": 1, "trapping": 1},
        region_progress=("great_plains",),
        notes="First elite tracker mission and relic-adjacent payoff.",
    ),
    ActivityDefinition(
        activity_id="new_hanover_hunting_loop",
        name="New Hanover Hunting Loop",
        xp=440,
        materials={"treated leather": 4, "gun oil concentrate": 1, "saint cards": 1},
        discovered_regions=("new_hanover",),
        farming_gains={"lane.hunter": 2, "lane.frontier_work": 1},
        network_gains={"track.jobs": 1},
        affinity_changes={"affinity.abigail": 4, "affinity.jack": 4},
        lifestyle_gains={"hunting": 1},
        completed_chapters=("chapter_4",),
        region_progress=("new_hanover",),
        notes="Opens cleaner farm-upgrade-return flow with hunting yields.",
    ),
    ActivityDefinition(
        activity_id="war_room_upgrade_push",
        name="Beecher's Hope War Room Push",
        xp=380,
        materials={"hardwood": 2, "preserved herbs": 2, "silver fittings": 1, "black powder bundles": 1},
        items={"War Room Supply Cache": 1},
        completed_trails=("trail.hub.map_board", "trail.house.war_room"),
        discovered_regions=("west_elizabeth", "great_plains", "new_hanover"),
        farming_gains={"lane.frontier_work": 1},
        network_gains={"track.jobs": 1, "track.stagecoaches": 1},
        affinity_changes={"affinity.abigail": 6, "affinity.jack": 5},
        lifestyle_gains={"homestead": 1, "field_medicine": 1},
        blueprints=("Field Cabinet Plan",),
        completed_chapters=("chapter_5",),
        region_progress=("west_elizabeth", "great_plains", "new_hanover"),
        notes="The ranch finally gets the map-board and support-cabinet push it needs to feel like a war room.",
    ),
    ActivityDefinition(
        activity_id="armadillo_supply_raid",
        name="Armadillo Supply Raid",
        xp=610,
        materials={"iron scrap": 5, "brass fittings": 1, "black powder bundles": 1},
        discovered_regions=("new_austin",),
        farming_gains={"lane.raider": 3},
        network_gains={"track.stagecoaches": 2, "track.contracts": 1},
        affinity_changes={"affinity.uncle": 12},
        lifestyle_gains={"salvaging": 1, "trade": 1},
        region_progress=("new_austin",),
        notes="Dangerous convoy hit that sets up stronger outlaw pressure.",
    ),
    ActivityDefinition(
        activity_id="silas_redd_showdown",
        name="Silas Redd Showdown",
        xp=900,
        materials={"engraved silver": 1, "elite insignias": 1, "tempered springs": 2},
        items={"Silas Redd's Repeater Receiver": 1},
        relics=1,
        boss_kills=1,
        completed_trails=("trail.boss.silas_redd", "trail.house.trophy_hall"),
        discovered_bosses=("boss.silas_redd", "boss.blackwater_broker_cell"),
        defeated_bosses=("boss.silas_redd",),
        discovered_regions=("great_plains", "west_elizabeth"),
        farming_gains={"lane.boss": 3, "lane.contract": 1},
        network_gains={"track.companions": 1, "track.contracts": 1},
        affinity_changes={"affinity.abigail": 5, "affinity.jack": 8, "affinity.uncle": 6},
        lifestyle_gains={"gunsmithing": 1, "homestead": 1},
        completed_chapters=("chapter_6",),
        region_progress=("great_plains", "west_elizabeth"),
        notes="First named boss kill and first real world-tier promotion anchor.",
    ),
    ActivityDefinition(
        activity_id="lemoyne_relic_expedition",
        name="Lemoyne Relic Expedition",
        xp=680,
        materials={"grave silver": 1, "silver fittings": 1, "collector bones": 1},
        relics=1,
        completed_trails=("trail.relic.lemoyne_whispers",),
        discovered_bosses=("boss.lemoyne_relic_keeper",),
        discovered_regions=("lemoyne",),
        farming_gains={"lane.boss": 1, "lane.hunter": 1},
        network_gains={"track.properties": 1},
        affinity_changes={"affinity.jack": 10},
        lifestyle_gains={"field_medicine": 1, "trapping": 1},
        blueprints=("Fence Relic Schematic",),
        region_progress=("lemoyne",),
        notes="Begins the early myth thread without fully breaking grounded tone.",
    ),
)


