from __future__ import annotations

SUPPORTED_LOCALES = ("en", "ko")

UI_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "app_title": "RDR2 Frontier Ledger Prototype",
        "header_title": "Frontier Ledger UI Prototype",
        "header_subtitle": "Prototype shell for combat, loot routing, and Beecher's Hope management",
        "compact_title": "Compact Frontier Ledger",
        "compact_hint": "F10 toggles this compact view. Use Beecher's Hope button for the full ledger.",
        "details": "Details",
        "compact_section_frontier": "Frontier Status",
        "compact_section_intel": "Quick Intel",
        "compact_section_ready": "Ready Now",
        "button_compact": "F10 Toggle",
        "button_full": "Beecher's Hope Ledger",
        "button_field": "Return To Field",
        "button_sim": "Load Simulated Run",
        "button_endgame": "Load Endgame",
        "button_reset": "Reset Baseline",
        "button_lang_en": "English",
        "button_lang_ko": "Korean",
        "overview_tab": "Overview",
        "trails_tab": "Active Trails",
        "map_tab": "Frontier Map",
        "homefront_tab": "Homefront",
        "affinity_tab": "Affinity",
        "farming_tab": "Farming",
        "network_tab": "Network",
        "world_tab": "World State",
        "ending_tab": "Ending",
        "stats_tab": "Stats",
        "gear_tab": "Gear",
        "armory_tab": "Armory",
        "skills_tab": "Skills",
        "perks_tab": "Perks",
        "crafting_tab": "Crafting",
        "dead_tab": "Ledger of the Dead",
        "collection_tab": "Collection",
        "upgrades_tab": "Workshop",
        "encyclopedia_tab": "Encyclopedia",
    },
    "ko": {
        "app_title": "프런티어 레저 프로토타입",
        "header_title": "프런티어 레저 UI 프로토타입",
        "header_subtitle": "전투, 드랍 라우팅, 비처스 호프 관리용 프로토타입 셸",
        "compact_title": "간이 프런티어 레저",
        "compact_hint": "F10으로 간이 레저를 토글합니다. 비처스 호프 버튼으로 전체 레저를 엽니다.",
        "details": "세부 정보",
        "compact_section_frontier": "프런티어 현황",
        "compact_section_intel": "빠른 정보",
        "compact_section_ready": "지금 가능",
        "button_compact": "F10 토글",
        "button_full": "비처스 호프 레저",
        "button_field": "필드로 복귀",
        "button_sim": "시뮬 상태 불러오기",
        "button_endgame": "엔드게임 불러오기",
        "button_reset": "기본 상태로",
        "button_lang_en": "English",
        "button_lang_ko": "한국어",
        "overview_tab": "개요",
        "trails_tab": "진행 추적",
        "map_tab": "프런티어 지도",
        "homefront_tab": "홈프론트",
        "affinity_tab": "친밀도",
        "farming_tab": "파밍",
        "network_tab": "네트워크",
        "world_tab": "월드 상태",
        "ending_tab": "엔딩",
        "stats_tab": "스탯",
        "gear_tab": "장비",
        "armory_tab": "병기",
        "skills_tab": "기술",
        "perks_tab": "퍽",
        "crafting_tab": "제작",
        "dead_tab": "망자의 장부",
        "collection_tab": "컬렉션",
        "upgrades_tab": "작업장",
        "encyclopedia_tab": "백과사전",
    },
}

GAMEPLAY_EXACT: dict[str, str] = {
    "A low-drama supply loop that still pushes the same pickup and storage flow without requiring a major boss fight.": "큰 보스전 없이도 같은 획득-보관 흐름을 검증하게 해 주는 저강도 보급 루프입니다.",
    "A Blackwater-side coach seizure loop that should turn a short fight into stored broker cargo and cleaner contract stock.": "짧은 전투를 저장 가능한 브로커 화물과 더 깔끔한 계약 재고로 바꾸는 블랙워터 마차 압수 루프입니다.",
    "A wrecked convoy loop that should feed scrap, fittings, picked cargo, and homebound storage.": "스크랩, 부품, 회수 화물, 거점 보관으로 이어지는 파손 호송대 루프입니다.",
    "A salvage return loop closer to home that still feeds the same pickup and storage chain through Beecher's Hope support stock.": "비처스 호프 지원 재고를 통해 같은 획득-보관 체인을 유지하는 근거리 회수 루프입니다.",
    "A hunting camp that converts the tracker fight into hides, herbs, picked trophies, and stashable field stock.": "추적조 전투를 가죽, 약초, 전리품, 보관 가능한 야전 재고로 바꾸는 사냥 캠프 루프입니다.",
    "An ore-and-camp route that should make resource collection feel like planned logistics rather than passive numbers.": "자원 수집이 수동적인 숫자가 아니라 계획된 물류처럼 느껴지게 만드는 광석/캠프 루프입니다.",
    "A lower-drama hunting route that still ends in tangible stored materials and archive-worthy trophy pieces.": "저강도 사냥 루트지만 실제 보관 재료와 기록할 만한 전리품으로 마감되는 루프입니다.",
    "An enforcer-backed cache meant to prove that rough combat routes can still become structured material income.": "거친 전투 루트도 구조화된 재료 수입으로 이어질 수 있음을 보여 주는 집행조 수호 캐시입니다.",
    "A harsher New Austin route where a short violent hit should still end in structured stored cargo instead of only loose scrap.": "짧고 거친 습격도 흩어진 스크랩이 아니라 구조화된 저장 화물로 마무리되어야 하는 뉴오스틴 루트입니다.",
    "A relic-side pickup loop that should feed myth materials, picked notes, and Jack-facing archive stock.": "신화 재료, 회수 문서, 잭의 기록 보관 재고를 함께 공급하는 유물 회수 루프입니다.",
    "A Lemoyne-side smuggler shack route that ties pressure combat to stored illicit stock and archive notes.": "압박 전투를 저장 가능한 밀수 물자와 기록 메모로 연결하는 르모인 밀수 오두막 루트입니다.",
    "A late ridge-cache route that should convert hard travel and pressure into meaningful stored late-game materials.": "고된 이동과 압박을 의미 있는 후반 저장 재료로 바꾸는 후반 능선 캐시 루트입니다.",
    "The first serious accuracy-and-pressure check once Blackwater stops feeling safe.": "블랙워터가 더 이상 안전지대로 느껴지지 않게 만드는 첫 정밀 사격/압박 체크입니다.",
    "The enforcer pair is the first encounter that really asks for grit, stagger, and stop-power tuning.": "집행조 조합은 근성, 경직 대응, 저지력 세팅을 진짜로 요구하는 첫 전투입니다.",
    "This encounter converts survival and flank tools into real value instead of flavor text.": "이 전투는 생존과 측면 공략 도구를 장식 문구가 아니라 실제 가치로 바꿉니다.",
    "This is the cleanest non-boss proving ground for Silas prep and anti-armor pressure.": "사일러스 준비와 대장갑 압박을 검증하기 가장 좋은 비보스 전장입니다.",
    "A precision-heavy boss whose defeat should turn contract work into real progression.": "처치 시 계약 루프를 실제 성장으로 바꿔야 하는 정밀 사격 중심 보스입니다.",
    "This boss is where tracking, burst damage, and relocation become real systems.": "추적, 순간 화력, 재배치가 진짜 시스템으로 느껴지는 보스전입니다.",
    "Silas should feel like the point where systems stop being notes and start becoming survival requirements.": "사일러스는 시스템이 메모 단계에서 벗어나 생존 필수 조건이 되는 분기점이어야 합니다.",
    "The Keeper should convert relic perks and clue work into concrete combat value.": "수호자는 유물 퍽과 단서 작업을 구체적인 전투 가치로 전환해야 합니다.",
    "The Surveyor is where the frontier war, relic route, and post-ending mastery all collide.": "측량자는 프런티어 전쟁, 유물 루트, 엔딩 이후 숙련이 한 번에 충돌하는 지점입니다.",
}

GAMEPLAY_FRAGMENTS: tuple[tuple[str, str], ...] = (
    ("Combat Role: ", "전투 역할: "),
    ("Combat: HP ", "전투: HP "),
    ("Resistances: ", "저항: "),
    ("Weaknesses: ", "약점: "),
    ("Projection: ", "예상 결과: "),
    ("Rounds: ", "라운드: "),
    ("Support: ", "지원: "),
    ("Support / phases: ", "지원 / 페이즈: "),
    ("Phases: ", "페이즈: "),
    ("Test Spawn: ", "테스트 소환: "),
    ("Spawn Note: ", "소환 메모: "),
    ("World Node: ", "월드 노드: "),
    ("Region: ", "지역: "),
    ("Category: ", "분류: "),
    ("Encounter won -> ", "전투 해결 -> "),
    ("Drop table -> materials ", "드랍 테이블 -> 재료 "),
    ("Picked and routed toward ", "획득 후 다음 보관소로 이동: "),
    ("First clear package -> ", "첫 클리어 패키지 -> "),
    ("Encounter: ", "전투: "),
    ("Drops: ", "드랍: "),
    ("First Clear: ", "첫 클리어: "),
    ("Stash Route: ", "보관 경로: "),
    ("Route Note: ", "루트 메모: "),
    ("Storage: ", "보관: "),
    ("Actual: ", "실효: "),
    ("field mats ", "필드 재료 "),
    ("stash mats ", "보관 재료 "),
    ("stash items ", "보관 아이템 "),
    ("routes ", "루트 "),
    ("Deposited materials -> ", "재료 보관 -> "),
    ("Deposited picked loot -> ", "획득 전리품 보관 -> "),
    ("No field cargo needed deposit at ", "다음 보관소로 옮길 필드 화물이 없습니다: "),
)


def ui_text(locale: str, key: str) -> str:
    normalized = locale if locale in SUPPORTED_LOCALES else "en"
    return UI_STRINGS.get(normalized, UI_STRINGS["en"]).get(key, UI_STRINGS["en"].get(key, key))


def gameplay_text(locale: str, text: str) -> str:
    if locale != "ko":
        return text
    translated = GAMEPLAY_EXACT.get(text, text)
    for source, target in GAMEPLAY_FRAGMENTS:
        translated = translated.replace(source, target)
    return translated
