from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def parse_strings(path: Path) -> dict[str, str]:
    entries: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        label, value = line.split("=", 1)
        entries[label.strip()] = value.strip()
    return dict(sorted(entries.items()))


def collect_characters(entries: dict[str, str], extra_texts: list[str]) -> list[str]:
    chars = {
        " ",
        "[",
        "]",
        "(",
        ")",
        "/",
        ":",
        ";",
        ",",
        ".",
        "-",
        "+",
        "'",
        '"',
        "!",
        "?",
        "|",
        "%",
    }
    for value in entries.values():
        normalized = value.replace("~n~", "\n")
        for ch in normalized:
            if ch not in {"\r", "\n"}:
                chars.add(ch)
    for value in extra_texts:
        normalized = value.replace("~n~", "\n")
        for ch in normalized:
            if ch not in {"\r", "\n"}:
                chars.add(ch)
    return sorted(chars, key=lambda item: ord(item))


def render_glyph(
    font: ImageFont.FreeTypeFont,
    ch: str,
    threshold: int,
    solid_threshold: int,
) -> dict[str, int | list[int]]:
    if ch == " ":
        advance = max(4, int(round(font.getlength(ch))) + 1)
        return {"width": 0, "height": 0, "advance": advance, "rows": [], "soft_rows": []}

    canvas = Image.new("L", (64, 64), 0)
    draw = ImageDraw.Draw(canvas)
    draw.text((6, 6), ch, font=font, fill=255)
    bbox = canvas.getbbox()
    if bbox is None:
        advance = max(1, int(round(font.getlength(ch))) + 1)
        return {"width": 0, "height": 0, "advance": advance, "rows": [], "soft_rows": []}

    cropped = canvas.crop(bbox)
    width, height = cropped.size
    rows: list[int] = []
    soft_rows: list[int] = []
    for y in range(height):
        mask = 0
        soft_mask = 0
        for x in range(width):
            pixel = cropped.getpixel((x, y))
            if pixel >= solid_threshold:
                mask |= 1 << x
            elif pixel >= threshold:
                soft_mask |= 1 << x
        rows.append(mask)
        soft_rows.append(soft_mask)

    advance = max(width + 1, int(round(font.getlength(ch))) + 1)
    return {"width": width, "height": height, "advance": advance, "rows": rows, "soft_rows": soft_rows}


def c_byte_string(value: str) -> str:
    out = ['"']
    for byte in value.encode("utf-8"):
        if 32 <= byte <= 126 and byte not in (34, 92):
            out.append(chr(byte))
        elif byte == 34:
            out.append('\\"')
        elif byte == 92:
            out.append("\\\\")
        else:
            out.append(f"\\{byte:03o}")
    out.append('"')
    return "".join(out)


def emit_header(entries: dict[str, str], glyphs: dict[int, dict[str, int | list[int]]], output: Path) -> None:
    max_height = max((glyph["height"] for glyph in glyphs.values()), default=1)
    line_advance = max_height + 1
    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/generate_bitmap_font.py. */")
    lines.append("#ifndef FRONTIER_BITMAP_FONT_GENERATED_H")
    lines.append("#define FRONTIER_BITMAP_FONT_GENERATED_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct FrontierBitmapGlyph {")
    lines.append("    uint32_t codepoint;")
    lines.append("    uint8_t width;")
    lines.append("    uint8_t height;")
    lines.append("    uint8_t advance;")
    lines.append(f"    uint32_t soft_rows[{max_height if max_height > 0 else 1}];")
    lines.append(f"    uint32_t rows[{max_height if max_height > 0 else 1}];")
    lines.append("} FrontierBitmapGlyph;")
    lines.append("")
    lines.append("typedef struct FrontierGeneratedTextEntry {")
    lines.append("    const char *label;")
    lines.append("    const char *value;")
    lines.append("} FrontierGeneratedTextEntry;")
    lines.append("")
    lines.append(f"#define FRONTIER_BITMAP_FONT_MAX_HEIGHT {max_height if max_height > 0 else 1}")
    lines.append(f"#define FRONTIER_BITMAP_FONT_LINE_ADVANCE {line_advance}")
    lines.append("")
    lines.append("static const FrontierBitmapGlyph kFrontierBitmapGlyphs[] = {")
    for codepoint in sorted(glyphs):
        glyph = glyphs[codepoint]
        soft_rows = list(glyph["soft_rows"]) + [0] * (max_height - len(glyph["soft_rows"]))
        rows = list(glyph["rows"]) + [0] * (max_height - len(glyph["rows"]))
        soft_row_text = ", ".join(f"0x{row:08X}u" for row in soft_rows)
        row_text = ", ".join(f"0x{row:08X}u" for row in rows)
        lines.append(
            f"    {{ 0x{codepoint:08X}u, {glyph['width']}, {glyph['height']}, {glyph['advance']}, {{ {soft_row_text} }}, {{ {row_text} }} }},"
        )
    lines.append("};")
    lines.append("")
    lines.append(f"static const int kFrontierBitmapGlyphCount = {len(glyphs)};")
    lines.append("")
    lines.append("static const FrontierGeneratedTextEntry kFrontierGeneratedTexts[] = {")
    for label, value in entries.items():
        lines.append(f"    {{ {c_byte_string(label)}, {c_byte_string(value)} }},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const int kFrontierGeneratedTextCount = {len(entries)};")
    lines.append("")
    lines.append("#endif")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strings-input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--font-path", default=r"C:\Windows\Fonts\malgun.ttf")
    parser.add_argument("--font-size", type=int, default=18)
    parser.add_argument("--threshold", type=int, default=48)
    parser.add_argument("--solid-threshold", type=int, default=96)
    parser.add_argument("--extra-strings-input", action="append", default=[])
    args = parser.parse_args()

    strings_input = Path(args.strings_input)
    output = Path(args.output)
    entries = parse_strings(strings_input)
    extra_texts: list[str] = []
    for extra_input in args.extra_strings_input:
        extra_path = Path(extra_input)
        if extra_path.exists():
            extra_texts.extend(extra_path.read_text(encoding="utf-8").splitlines())
    characters = collect_characters(entries, extra_texts)
    font = ImageFont.truetype(args.font_path, args.font_size)
    glyphs: dict[int, dict[str, int | list[int]]] = {}
    for ch in characters:
        glyphs[ord(ch)] = render_glyph(font, ch, args.threshold, args.solid_threshold)

    emit_header(entries, glyphs, output)
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
